        <section>
          <p>Les messages d'erreur :</p>
        <?php if (isset($errors) && count($errors) > 0) : ?>
            <div>
              <img src="../img/warning.gif" alt="Triangle warning"/>
            </div>
            <div>
              <ul>
                <?php foreach ($errors as $error) : ?>
                  <li><?= $error; ?></li>
                <?php endforeach; ?>
              </ul>
            </div>
        <?php endif; ?>
        
        <?php if (isset($valids) && count($valids) > 0) : ?>
              <div>
                <img src="img/validation.png" alt="Validation"/>
              </div>
            <div>
              <ul>
                <?php foreach ($valids as $valid) : ?>
                  <li><?= $valid; ?></li>
                <?php endforeach; ?>
              </ul>
            </div>
        <?php endif; ?>
        </section>
        
        <form  method="POST" action="index.php?route=changePassword">
            
            <label for="oldPass">Vieux Mot de Passe</label>
            <input type="password" name="oldPass" value=""/>
            
            <label for="newPass">Nouveau Mot de Passe</label>
            <input type="password" name="newPass" value=""/>
            
            <label for="newPassCheck">Répetez Nouveau Mot de Passe</label>
            <input type="password" name="newPassCheck" value=""/>
            
            </br>
            <input type="submit" value="Change Password" />
        </form>